<?xml version="1.0"?>
<!DOCTYPE module [

<!ELEMENT module (module|property)*>
<!ATTLIST module name NMTOKEN #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
        name NMTOKEN #REQUIRED
        value CDATA #REQUIRED>
]>

<module name="Checker">
    <module name="SuppressionFilter">
        <property name="file" value="${suppressions-file}"/>
    </module>
    
    <module name="TreeWalker">

        <module name="EmptyBlock">
            <property name="option" value="text" />
        </module>
        <module name="EqualsHashCode"/>
        <module name="BooleanExpressionComplexity">
            <property name="max" value="4" />
        </module>
        <module name="DefaultComesLast"/>
        <module name="EmptyStatement"/>
        <module name="FallThrough"/>
        
        <module name="NestedForDepth">
            <property name="max" value="2"/>
        </module>
        <module name="NestedIfDepth">
            <property name="max" value="2"/>
        </module>
        <module name="NestedTryDepth">
            <property name="max" value="2"/>
        </module>
        <module name="NoClone"/>
        <module name="NoFinalizer"/>
        <module name="OneStatementPerLine"/>
        <module name="RedundantImport"/>
        <module name="UnusedImports"/>
        <module name="StringLiteralEquality"/>
        <module name="SuperClone"/>
        <module name="SuperFinalize"/>
        <module name="ArrayTrailingComma"/>
        <module name="StringLiteralEquality"/>
        <module name="InnerAssignment"/>
        
        <module name="IllegalInstantiation">
            <property name="classes" value="java.lang.Boolean"/>
        </module>
        <module name="PackageDeclaration"/>
        <module name="JUnitTestCase"/>
        
        <module name="MethodCount">
            <property name="maxTotal" value="100"/>
        </module>
         <module name="MissingDeprecated"/>
        <module name="MutableException"/>
        <module name="ThrowsCount">
            <property name="max" value="2"/>
        </module>
        <module name="NPathComplexity">
            <property name="max" value="150"/>
        </module>
        <module name="OuterTypeFilename"/>
        <module name="UpperEll"/>
        <module name="LineLength">
            <property name="max" value="150" />
        </module>
        <module name="NeedBraces">
            <property name="tokens" value="LITERAL_IF, LITERAL_ELSE"/>
        </module>
        <module name="EqualsAvoidNull"/>
        
<!--  Currently Broken -->


<!--        <module name="InnerTypeLast"/>-->
<!--        <module name="ReturnCount">-->
<!--            <property name="max" value="3"/>-->
<!--        </module>-->
<!--        <module name="ModifierOrder"/>-->
<!--        <module name="CyclomaticComplexity">-->
<!--            <property name="max" value="8"/>-->
<!--        </module>-->

<!--        <module name="MultipleStringLiterals">-->
<!--            <property name="allowedDuplicates" value="2" />-->
<!--        </module>-->
<!--        <module name="HiddenField">-->
<!--            <property name="ignoreConstructorParameter" value="true"/>-->
<!--            <property name="ignoreSetter" value="true"/>-->
<!--        </module>-->
<!--        <module name="MethodLength">-->
<!--            <property name="max" value="80" />-->
<!--        </module>-->
<!--            <module name="AnonInnerLength">-->
<!--                <property name="max" value="60" />-->
<!--            </module>-->

<!-- Longer term fixes, Don't fix yet -->
<!-- Extract magic numbers to a property file -->
<!--        <module name="MagicNumber" />-->

    </module>
        
<!--    <module name="StrictDuplicateCode">-->
<!--        <property name="min" value="20"/>-->
<!--    </module>-->
        
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf" />
    </module> 
    <module name="FileTabCharacter" />
    <module name="FileLengthCheck" >
        <property name="max" value="1400" />
    </module>
    
</module>
